import 'package:flutter/material.dart';
import 'package:the_widgets/every_widgets/about_dialog.dart';

class ExampleDestination {
  const ExampleDestination(this.label, this.icon, this.selectedIcon);
  final String label;
  final Widget icon;
  final Widget selectedIcon;

  static final widgetsList = [
    "About Dialog",
    "About List Tile",
    "Absorb Pointer",
    "Alert Dialog",
    "Align",
    "Animated Align",
    "Animated Builder",
    "Animated Container",
    "Animated Cross Fade",
    "Animated Default Text Style",
    "Animated Icon",
    "Animated List",
    "Animated List State",
    "Animated Model Barrier",
    "Animated Opacity",
    "Animated Padding",
    "Animated Physical Model",
    "Animated Positioned",
    "Animated Rotation",
    "Animated Size",
    "Animated Switcher",
    "Animated Widget",
    "App Bar",
    "Aspect Ratio",
    "Auto complete",
    "Backdrop filter",
    "Badge",
    "Banner",
    "Baseline",
    "Block Semantics",
    "Bottom Navigation Bar",
    "Bottom Sheet",
    "Builder",
    "Card",
    "Center",
    "Checkbox",
    "Checkbox List Tile",
    "Chip",
    "Choice Chip",
    "Circle Avatar",
    "Circle Progress Indicator",
    "Clip Oval",
    "Clip Path",
    "Clip R-Rect",
    "Clip Rect",
    "Close Button",
    "Color Filtered",
    "Colored Box",
    "Column",
    "Constrained Box",
    "Container",
    "Cupertino Action Sheet Action",
    "Cupertino Activity Indicator",
    "Cupertino Alert Dialog",
    "Cupertino App",
    "Cupertino Button",
    "Cupertino Context Menu",
    "Cupertino Date Picker",
    "Cupertino Page Route",
    "Cupertino Page Scaffold",
    "Cupertino Picker",
    "Cupertino Popup Surface",
    "Cupertino Scrollbar",
    "Cupertino Search Text Field",
    "Cupertino Segmented Control",
    "Cupertino Slider",
    "Cupertino Sliding Segmented Control",
    "Cupertino Switch",
    "Cupertino Tabbar",
    "Cupertino Tab Scaffold",
    "Cupertino Tab View",
    "Cupertino Text Field",
    "Custom Paint",
    "Custom Scoll View",
    "Data Table",
    "Date Picker",
    "Date Range Picker",
    "Decorated Box",
    "Decorated Box Transition",
    "Default Text Style",
    "Dismissible",
    "Divider",
    "Drag Target",
    "Dragable",
    "Dragable Scrollable Sheet",
    "Drawer",
    "Drawer Header",
    "Dropdown Button",
    "Elevated Button",
    "Error Widget",
    "Expand Icon",
    "Expanded",
    "Expansion Panel List",
    "Expansion Tile",
    "Fade In Image",
    "Fade Transition",
    "Filled Button",
    "Filter Chip",
    "Fitted Box",
    "Flexible",
    "Floating Action Button",
    "Flow",
    "Flutter Error Detail",
    "Flutter Logo",
    "Form",
    "Fractional Transition",
    "Fractionaly Sized Box",
    "Future Builder",
    "Gesture Detector",
    "Grid Paper",
    "Grid Tile",
    "Grid Tile Bar",
    "Grid View",
    "Hero",
    "Icon",
    "Icon Button",
    "Ignore Pointer",
    "Image",
    "Image Network",
    "Indexed Stack",
    "Inx Well",
    "Input Chip",
    "Interactive Viewer",
    "Layout Builder",
    "Limited Box",
    "Linear Progress Indicator",
    "List Body",
    "List Tile",
    "List View",
    "List Wheel Scroll View",
    "Listener",
    "Long Press Draggable",
    "Material App",
    "Material Banner",
    "Material Button",
    "Merge Semantics",
    "Modal Barrier",
    "Mouse Cursor",
    "Mouse Region",
    "Navigation Bar",
    "Navigation Drawer",
    "Navigation Drawer Destination",
    "Notification Listener",
    "Offstage",
    "Opacity",
    "Orientation Builder",
    "Outlined Button",
    "Overflow Bar",
    "Overflow Box",
    "Padding",
    "Pageview",
    "Physical Model",
    "Physical Shape",
    "Place Holder",
    "Platform Menu",
    "Popup Menu Button",
    "Positioned",
    "Positioned Transition",
    "Preferred Size",
    "Radio",
    "Radio List Tile",
    "Range Slider",
    "Raw Auto Complete",
    "Raw Keyboard Listener",
    "Raw Chip",
    "Refresh Indicator",
    "Re-Orderable ListView",
    "Rich Text",
    "Rotated Box",
    "Rotated Transition",
    "Row",
    "Scaffold",
    "Scale Transition",
    "ScrollBar",
    "SearchBar",
    "Selectable Text",
    "Semantics",
    "Shader Mask",
    "Shortcuts",
    "Simple Dialog",
    "Single Child ScrolView",
    "Size Transition",
    "Sized Box",
    "Sized Overflow Box",
    "Slide Transition",
    "Slider",
    "Sliver Appbar",
    "Sliver Fixed Extent List",
    "Sliver Grid",
    "Sliver List",
    "Sliver Opacity",
    "Sliver Padding",
    "Sliver To Box Adapter",
    "Snack Bar",
    "Spacer",
    "Stack",
    "Stepper",
    "Stream Builder",
    "Switch List Tile",
    "Switch",
    "Tab Bar",
    "Tab Page Selector",
    "Table",
    "Text",
    "Text Button",
    "Text Field",
    "Text Form Field",
    "Text Span",
    "Theme",
    "Toggle Button",
    "Tool Tip",
    "Transform",
    "Tween Animation Builder",
    "Value Listenable Builder",
    "Vertical Divider",
    "Visibility",
    "Will Pop Scope",
    "Wrap",
  ];
}
